theme: jekyll-theme-cayman
title: 1st International Workshop on Anti-Patterns for Software Analytics (APSA)
description: In conjunction with ICSE 2018, May 27 - 3 June 2018, Gothenburg, Sweden
github.is_project_page: false
author:
  name: Steffen Herbold
  twitter: HerboldSteffen
